// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_unikraft

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func UnikraftProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type UnikraftModel struct {
}
