// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unikraft_volume

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnikraftVolumeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"details": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to include details about the volume in the response.  By\ndefault this is set to true, meaning that all information about the\nvolume will be included in the response.  If set to false, only the\nbasic information about the volume will be included, such as its name\nand UUID.",
				MarkdownDescription: "Whether to include details about the volume in the response.  By\ndefault this is set to true, meaning that all information about the\nvolume will be included in the response.  If set to false, only the\nbasic information about the volume will be included, such as its name\nand UUID.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the volume.\n\nThis is a human-readable name that can be used to identify the volume. The name must be unique within the context of your account. If no name is specified, a random name of the form `vol-X` is generated for you, where `X` is a 5-character long random alphanumeric suffix. The name can also be used to identify the volume in API calls.",
				MarkdownDescription: "The name of the volume.\n\nThis is a human-readable name that can be used to identify the volume. The name must be unique within the context of your account. If no name is specified, a random name of the form `vol-X` is generated for you, where `X` is a 5-character long random alphanumeric suffix. The name can also be used to identify the volume in API calls.",
			},
			"size_mb": schema.Int64Attribute{
				Required:            true,
				Description:         "The size of the volume in megabytes.",
				MarkdownDescription: "The size of the volume in megabytes.",
			},
		},
	}
}

type UnikraftVolumeModel struct {
	Details types.Bool   `tfsdk:"details"`
	Name    types.String `tfsdk:"name"`
	SizeMb  types.Int64  `tfsdk:"size_mb"`
}
