// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unikraft_certificate

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnikraftCertificateResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"chain": schema.StringAttribute{
				Required:            true,
				Description:         "The chain of the certificate.",
				MarkdownDescription: "The chain of the certificate.",
			},
			"cn": schema.StringAttribute{
				Required:            true,
				Description:         "The common name (CN) of the certificate.",
				MarkdownDescription: "The common name (CN) of the certificate.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the certificate (optional).",
				MarkdownDescription: "The name of the certificate (optional).",
			},
			"pkey": schema.StringAttribute{
				Required:            true,
				Description:         "The private key of the certificate.",
				MarkdownDescription: "The private key of the certificate.",
			},
			"uuid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The UUID of the certificate.",
				MarkdownDescription: "The UUID of the certificate.",
			},
		},
	}
}

type UnikraftCertificateModel struct {
	Chain types.String `tfsdk:"chain"`
	Cn    types.String `tfsdk:"cn"`
	Name  types.String `tfsdk:"name"`
	Pkey  types.String `tfsdk:"pkey"`
	Uuid  types.String `tfsdk:"uuid"`
}
