name: GitHub Actions linting

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  action-lint:
    name: Action Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install action linter
        run: |
          mkdir -p "$HOME"/.local/bin
          curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- latest "$HOME"/.local/bin

      - name: Check that all workflows are valid
        run: actionlint -verbose
